spring:
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      routes:
        - id: gulimall-seckill
          uri: lb://gulimall-seckill
          predicates:
            - Path=/api/seckill/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        #将路径为Path=/api/**转发至后台管理
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}

        #将主机地址为search.gulimall.com转发至gulimall-search
        - id: gulimall_serach_host
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com

        #将主机地址为auth.gulimall.com转发至gulimall-auth
        - id: gulimall_auth_host
          uri: lb://gulimall-auth-server
          predicates:
            - Host=auth.gulimall.com


      #将主机地址为search.gulimall.com转发至gulimall-search
        - id: gulimall_cart_host
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.gulimall.com

        #将主机地址为order.gulimall.com转发至gulimall-order
        - id: gulimall_order_host
          uri: lb://gulimall-order
          predicates:
            - Host=order.gulimall.com

        #将主机地址为seckill.gulimall.com转发至gulimall-seckill
        - id: gulimall_seckill_host
          uri: lb://gulimall-seckill
          predicates:
            - Host=seckill.gulimall.com

        #将主机地址为**.gulimall.com转发至gulimall-product
        - id: gulimall_host
          uri: lb://gulimall-product
          predicates:
            - Host=**.gulimall.com
    sentinel:
      transport:
        dashboard: localhost:8080
    loadbalancer:
      health-check:
        interval: 5s
        refetch-instances-interval: 5s
      service-discovery:
        timeout: 1s
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: debug